name: CI

on:
  push:
    branches: [master]
    paths:
      - grammar.js
      - src/**
      - bindings/**
      - binding.gyp
  pull_request:
    paths:
      - grammar.js
      - src/**
      - bindings/**
      - binding.gyp

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test parser
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
    steps:
      - name: Set up repository
        uses: tree-sitter-grammars/actions/setup@main
        with:
          node-version: ${{vars.NODE_VERSION}}
      - name: Clone OpenSSL examples
        uses: actions/checkout@v4
        with:
          path: examples/openssl
          repository: openssl/openssl
          sparse-checkout: test/certs
          ref: fd27a7e4f829e6a9b0d240efcabc39a971b8f511
      - name: Run tests
        uses: tree-sitter-grammars/actions/test@main
        with:
          test-library: ${{runner.os == 'Linux'}}
          examples: |-
            examples/openssl/test/certs/*.pem
            examples/openssl/test/certs/*.csr
            examples/openssl/test/certs/*.crt
            examples/openssl/test/certs/*.key
