name: CI

on:
  push:
    branches: [master]
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
  pull_request:
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test parser
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v2
      - name: Clone OpenSSL examples
        uses: actions/checkout@v4
        with:
          path: examples/openssl
          repository: openssl/openssl
          sparse-checkout: test/certs
      - name: Run tests
        uses: tree-sitter/parser-test-action@v2
      - name: Parse examples
        uses: tree-sitter/parse-action@v4
        with:
          files: |-
            examples/openssl/test/certs/*.pem
            examples/openssl/test/certs/*.csr
            examples/openssl/test/certs/*.crt
            examples/openssl/test/certs/*.key
