name: Release

on:
  push:
    tags: ["*"]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  github:
    uses: tree-sitter/workflows/.github/workflows/release.yml@main
    with:
      attestations: true
    permissions:
      contents: write
      id-token: write
      attestations: write
